"use client"

import { useState } from "react"
import Link from "next/link"
import Image from "next/image"
import { useSearchParams } from "next/navigation"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"

export default function ProductGrid() {
  const searchParams = useSearchParams()
  const category = searchParams.get("category")

  // This would normally be fetched from the server
  const [products, setProducts] = useState([
    {
      id: 1,
      name: "Ball Valve",
      image: "/Ball_Valve.webp",
      category: "mechanical",
      slug: "ball-valve",
      isNew: false,
    },
    {
      id: 2,
      name: "Bearings",
      image: "/Bearings.jpg",
      category: "mechanical",
      slug: "bearings",
      isNew: false,
    },
    {
      id: 3,
      name: "Blind Flange",
      image: "/Blind_Flange.jpg",
      category: "mechanical",
      slug: "blind-flange",
      isNew: false,
    },
    {
      id: 4,
      name: "Bolts",
      image: "/Bolts.jpg",
      category: "mechanical",
      slug: "bolts",
      isNew: false,
    },
    {
      id: 5,
      name: "Butterfly Valve",
      image: "/Butterfly_Valve.jpg",
      category: "mechanical",
      slug: "butterfly-valve",
      isNew: false,
    },
    {
      id: 6,
      name: "Buttweld Pipe Fitting",
      image: "/Buttweld_Pipe_Fitting.webp",
      category: "mechanical",
      slug: "buttweld-pipe-fitting",
      isNew: false,
    },
    {
      id: 7,
      name: "Chain",
      image: "/Chain.webp",
      category: "mechanical",
      slug: "chain",
      isNew: false,
    },
    {
      id: 8,
      name: "Clamps",
      image: "/Clamps.jpg",
      category: "mechanical",
      slug: "clamps",
      isNew: false,
    },
    {
      id: 9,
      name: "CS Pipe",
      image: "/CS_Pipe.jpg",
      category: "mechanical",
      slug: "cs-pipe",
      isNew: false,
    },
    {
      id: 10,
      name: "Electrical Components",
      image: "/electrical.jpg",
      category: "electrical",
      slug: "electrical-components",
      isNew: true,
    },
    {
      id: 11,
      name: "Electrical Supplies",
      image: "/electrical2.jpg",
      category: "electrical",
      slug: "electrical-supplies",
      isNew: false,
    },
    {
      id: 12,
      name: "Expansion Joint",
      image: "/Expansion_Joint.png",
      category: "mechanical",
      slug: "expansion-joint",
      isNew: false,
    },
    {
      id: 13,
      name: "Gaskets",
      image: "/Gaskets.jpg",
      category: "mechanical",
      slug: "gaskets",
      isNew: false,
    },
    {
      id: 14,
      name: "Gate Valve",
      image: "/Gate_Valve.jpg",
      category: "mechanical",
      slug: "gate-valve",
      isNew: false,
    },
    {
      id: 15,
      name: "GI Pipe",
      image: "/GI_Pipe.webp",
      category: "mechanical",
      slug: "gi-pipe",
      isNew: false,
    },
    {
      id: 16,
      name: "Globe Valve",
      image: "/Globe_Valve.jpg",
      category: "mechanical",
      slug: "globe-valve",
      isNew: true,
    },
    {
      id: 17,
      name: "Hose",
      image: "/Hose.jpg",
      category: "mechanical",
      slug: "hose",
      isNew: false,
    },
    {
      id: 18,
      name: "Lap Joint Flange",
      image: "/Lap-Joint-Flange.webp",
      category: "mechanical",
      slug: "lap-joint-flange",
      isNew: false,
    },
    {
      id: 19,
      name: "Mechanical Components",
      image: "/Mechanical.jpg",
      category: "mechanical",
      slug: "mechanical-components",
      isNew: false,
    },
    {
      id: 20,
      name: "Nuts",
      image: "/Nuts.jpg",
      category: "mechanical",
      slug: "nuts",
      isNew: false,
    },
    {
      id: 21,
      name: "Pulley",
      image: "/Pulley.jpeg",
      category: "mechanical",
      slug: "pulley",
      isNew: false,
    },
    {
      id: 22,
      name: "PVC Pipe",
      image: "/PVC_Pipe.webp",
      category: "mechanical",
      slug: "pvc-pipe",
      isNew: false,
    },
    {
      id: 23,
      name: "Safety Equipment",
      image: "/safety.webp",
      category: "safety-equipment",
      slug: "safety-equipment",
      isNew: true,
    },
    {
      id: 24,
      name: "Seals",
      image: "/Seals.jpg",
      category: "mechanical",
      slug: "seals",
      isNew: false,
    },
    {
      id: 25,
      name: "Shaft",
      image: "/Shaft.webp",
      category: "mechanical",
      slug: "shaft",
      isNew: false,
    },
    {
      id: 26,
      name: "Socketweld Pipe Fitting",
      image: "/Socketweld_Pipe_Fitting.webp",
      category: "mechanical",
      slug: "socketweld-pipe-fitting",
      isNew: false,
    },
    {
      id: 27,
      name: "SORF Flange",
      image: "/Sorf_Flange.jpg",
      category: "mechanical",
      slug: "sorf-flange",
      isNew: false,
    },
    {
      id: 28,
      name: "SS Tube",
      image: "/SS_Tube.webp",
      category: "mechanical",
      slug: "ss-tube",
      isNew: false,
    },
    {
      id: 29,
      name: "Threaded Pipe Fitting",
      image: "/Threaded_Pipe_Fitting.jpg",
      category: "mechanical",
      slug: "threaded-pipe-fitting",
      isNew: false,
    },
    {
      id: 30,
      name: "Washers",
      image: "/Washers.jpg",
      category: "mechanical",
      slug: "washers",
      isNew: false,
    },
    {
      id: 31,
      name: "WNRF Flange",
      image: "/WNRF_Flange.jpg",
      category: "mechanical",
      slug: "wnrf-flange",
      isNew: false,
    },
    {
      id: 32,
      name: "Copper Bus Bar Connectors",
      image: "/Busbars.jpg",
      category: "electrical",
      slug: "copper-bus-bar-connectors",
      isNew: false,
    },
    {
      id: 33,
      name: "Power Cable",
      image: "/unarmoured-cable.png",
      category: "electrical",
      slug: "power-cable",
      isNew: false,
    },
    {
      id: 34,
      name: "Fluke T6-600 Electrical Tester",
      image: "/Tester.jpg",
      category: "testing-equipment",
      slug: "fluke-t6-600-tester",
      isNew: true,
    },
    {
      id: 35,
      name: "Wire Terminals",
      image: "/Terminals.webp",
      category: "electrical",
      slug: "wire-terminals",
      isNew: false,
    },
    {
      id: 36,
      name: "Distribution Panel Board",
      image: "/Distribution_Panel.webp",
      category: "electrical",
      slug: "distribution-panel-board",
      isNew: true,
    },
    {
      id: 37,
      name: "Industrial Relays",
      image: "/Relays.webp",
      category: "electrical",
      slug: "industrial-relays",
      isNew: false,
    },
    {
      id: 38,
      name: "Digital Multimeter",
      image: "/Multimeter.jpeg",
      category: "testing-equipment",
      slug: "digital-multimeter",
      isNew: false,
    },
    {
      id: 39,
      name: "MCB Circuit Breakers",
      image: "/MCBs.webp",
      category: "electrical",
      slug: "mcb-circuit-breakers",
      isNew: false,
    },
    {
      id: 40,
      name: "Schneider MCCB",
      image: "/MCCB.jpg",
      category: "electrical",
      slug: "schneider-mccb",
      isNew: true,
    },
    {
      id: 41,
      name: "Industrial Switchgear",
      image: "/Switchgear.jpg",
      category: "electrical",
      slug: "industrial-switchgear",
      isNew: false,
    },
    {
      id: 42,
      name: "Electrical Contactor",
      image: "/Contactor.webp",
      category: "electrical",
      slug: "electrical-contactor",
      isNew: false,
    },
    {
      id: 43,
      name: "Cable Lugs",
      image: "/Lugs.webp",
      category: "electrical",
      slug: "cable-lugs",
      isNew: false,
    },
    {
      id: 44,
      name: "Armored Power Cable",
      image: "/armored-cable.jpg",
      category: "electrical",
      slug: "armored-power-cable",
      isNew: true,
    },
    {
      id: 45,
      name: "Cable Tray Systems",
      image: "/Cable_Tray.webp",
      category: "electrical",
      slug: "cable-tray-systems",
      isNew: false,
    },
    {
      id: 46,
      name: "Industrial Lighting Panel",
      image: "/Industrial_Lighting_Fixtures.jpg",
      category: "electrical",
      slug: "industrial-lighting-panel",
      isNew: false,
    },
    {
      id: 47,
      name: "Explosion Proof Light",
      image: "/Explosion_Proof_Lighting.jpg",
      category: "electrical",
      slug: "explosion-proof-light",
      isNew: true,
    },
    {
      id: 48,
      name: "Cable Glands",
      image: "/Cable_Glands.jpg",
      category: "electrical",
      slug: "cable-glands",
      isNew: false,
    },
    {
      id: 49,
      name: "Electrical Conduit",
      image: "/Conduit.jpg",
      category: "electrical",
      slug: "electrical-conduit",
      isNew: false,
    },
    {
      id: 50,
      name: "Fluke Clamp Meter",
      image: "/Clamp_Meter.jpg",
      category: "testing-equipment",
      slug: "fluke-clamp-meter",
      isNew: true,
    },
    {
      id: 51,
      name: "High Voltage Insulators",
      image: "/Insulators.jpeg",
      category: "electrical",
      slug: "high-voltage-insulators",
      isNew: false,
    },
    {
      id: 52,
      name: "Cable Ties",
      image: "/Cable_Ties.jpg",
      category: "electrical",
      slug: "cable-ties",
      isNew: false,
    },
    {
      id: 53,
      name: "Earthing Materials",
      image: "/Earthing Materials.jpg",
      category: "electrical",
      slug: "earthing-materials",
      isNew: false,
    },
    {
      id: 54,
      name: "High Voltage Line Post Insulator",
      image: "/Insulators.jpeg",
      category: "electrical",
      slug: "line-post-insulator",
      isNew: true,
    },
    {
      id: 55,
      name: "Industrial Power Distribution Box",
      image: "/Distribution_Panel.webp",
      category: "electrical",
      slug: "power-distribution-box",
      isNew: true,
    },
    {
      id: 56,
      name: "Earthing Rod Kit",
      image: "/Earthing Materials.jpg",
      category: "electrical",
      slug: "earthing-rod-kit",
      isNew: false,
    },
    {
      id: 57,
      name: "Safety Gloves",
      image: "/Gloves+.webp",
      category: "safety-equipment",
      slug: "safety-gloves",
      isNew: false,
    },
    {
      id: 58,
      name: "Safety Helmet",
      image: "/Helmet+.jpg",
      category: "safety-equipment",
      slug: "safety-helmet",
      isNew: false,
    },
    {
      id: 59,
      name: "Welding Machine Kit",
      image: "/Welding_Accessories+.webp",
      category: "welding-equipment",
      slug: "welding-machine-kit",
      isNew: true,
    },
    {
      id: 60,
      name: "High Visibility Safety Vest",
      image: "/Safety_Vest+.jpg",
      category: "safety-equipment",
      slug: "safety-vest",
      isNew: false,
    },
    {
      id: 61,
      name: "Industrial Safety Shoes",
      image: "/Shoes+.jpeg",
      category: "safety-equipment",
      slug: "safety-shoes",
      isNew: false,
    },
    {
      id: 62,
      name: "Industrial Lubricant",
      image: "/Lubricant+.webp",
      category: "maintenance-supplies",
      slug: "industrial-lubricant",
      isNew: false,
    },
    {
      id: 63,
      name: "Industrial Brushes",
      image: "/Industrial_Brushes+.jpg",
      category: "maintenance-supplies",
      slug: "industrial-brushes",
      isNew: false,
    },
    {
      id: 64,
      name: "Industrial Rollers",
      image: "/industrial-rollers+.webp",
      category: "maintenance-supplies",
      slug: "industrial-rollers",
      isNew: false,
    },
    {
      id: 65,
      name: "Industrial Paints",
      image: "/industrial-paints+.jpg",
      category: "maintenance-supplies",
      slug: "industrial-paints",
      isNew: true,
    },
    {
      id: 66,
      name: "Packing Materials",
      image: "/Packing_Material+.jpg",
      category: "packaging",
      slug: "packing-materials",
      isNew: false,
    },
    {
      id: 67,
      name: "Industrial Adhesive Tapes",
      image: "/tapes+.jpg",
      category: "packaging",
      slug: "adhesive-tapes",
      isNew: false,
    },
    {
      id: 68,
      name: "Metal Rollers",
      image: "/Shaft.webp",
      category: "mechanical",
      slug: "metal-rollers",
      isNew: false,
    },
    {
      id: 69,
      name: "Industrial Sealants",
      image: "/sealants.webp",
      category: "maintenance-supplies",
      slug: "industrial-sealants",
      isNew: false,
    },
    {
      id: 70,
      name: "Electrode Cable Set",
      image: "/Electrodes+.jpg",
      category: "electrical",
      slug: "electrode-cable-set",
      isNew: false,
    },
    {
      id: 72,
      name: "Industrial Cleaning Brush Set",
      image: "/Industrial_Brushes+.jpg",
      category: "maintenance-supplies",
      slug: "cleaning-brush-set",
      isNew: false,
    }
  ])

  const filteredProducts = category ? products.filter((product) => product.category === category) : products

  return (
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {filteredProducts.map((product) => (
        <Link key={product.id} href={`/products/${product.slug}`}>
          <Card className="overflow-hidden hover:shadow-lg transition-shadow duration-300 h-full">
            <div className="relative">
              <div className="relative h-64">
                <Image src={product.image || "/placeholder.svg"} alt={product.name} fill className="object-cover" />
              </div>
              {product.isNew && <Badge className="absolute top-2 right-2 bg-green-600">New</Badge>}
            </div>
            <CardContent className="p-4">
              <div className="text-sm text-gray-500 mb-2">
                {product.category.replace(/-/g, " ").replace(/\b\w/g, (l) => l.toUpperCase())}
              </div>
              <h3 className="font-semibold text-lg">{product.name}</h3>
            </CardContent>
            <CardFooter className="p-4 pt-0">
              <Button className="w-full bg-red-600 hover:bg-red-700">View Details</Button>
            </CardFooter>
          </Card>
        </Link>
      ))}
    </div>
  )
}
